# admix.Dataset

We introduce the central data stuctures used in this package.

- `dset.geno`: genotype (``n_snp``, ``n_indiv``, ``n_ploidy``)
- `dset.lanc`: local ancestry (``n_snp``, ``n_indiv``, ``n_ploidy``)
- `dset.snp`: information about SNPs (``n_snp``, ``n_snp_feature``)
- `dset.indiv`: information about individuals (``n_indiv``, ``n_indiv_feature``)

Central in python API is the admix.Dataset class, which support various convenient operations for manipulating large on-disk data sets.

In [1]:
import admix

# load example data
dset = admix.io.read_dataset("example_data/CEU-YRI")

In [2]:
# overview of data set
dset

admix.Dataset object with n_snp x n_indiv = 15357 x 10000, n_anc=2
	snp: 'CHROM', 'POS', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO'

In [3]:
# SNP attributes, CHROM (chromosomes), POS (positions), REF (reference allele), ALT (alternative allele), etc.
# we have also precomputed FREQ1, FREQ2 as ancestry-specific allele frequencies
dset.snp

                 CHROM       POS REF ALT QUAL FILTER INFO
snp
22:16406147:A:G     22  16406147   A   G    .      .    .
22:16551808:T:C     22  16551808   T   C    .      .    .
22:16573830:T:C     22  16573830   T   C    .      .    .
22:16575525:T:C     22  16575525   T   C    .      .    .
22:16576248:G:T     22  16576248   G   T    .      .    .
...                ...       ...  ..  ..  ...    ...  ...
22:50739662:G:A     22  50739662   G   A    .      .    .
22:50743331:A:G     22  50743331   A   G    .      .    .
22:50772964:T:C     22  50772964   T   C    .      .    .
22:50774447:A:C     22  50774447   A   C    .      .    .
22:50780578:G:A     22  50780578   G   A    .      .    .

[15357 rows x 7 columns]

In [4]:
# individual attributes
dset.indiv

Empty DataFrame
Columns: []
Index: [Sample_1, Sample_2, Sample_3, Sample_4, Sample_5, Sample_6, Sample_7, Sample_8, Sample_9, Sample_10, Sample_11, Sample_12, Sample_13, Sample_14, Sample_15, Sample_16, Sample_17, Sample_18, Sample_19, Sample_20, Sample_21, Sample_22, Sample_23, Sample_24, Sample_25, Sample_26, Sample_27, Sample_28, Sample_29, Sample_30, Sample_31, Sample_32, Sample_33, Sample_34, Sample_35, Sample_36, Sample_37, Sample_38, Sample_39, Sample_40, Sample_41, Sample_42, Sample_43, Sample_44, Sample_45, Sample_46, Sample_47, Sample_48, Sample_49, Sample_50, Sample_51, Sample_52, Sample_53, Sample_54, Sample_55, Sample_56, Sample_57, Sample_58, Sample_59, Sample_60, Sample_61, Sample_62, Sample_63, Sample_64, Sample_65, Sample_66, Sample_67, Sample_68, Sample_69, Sample_70, Sample_71, Sample_72, Sample_73, Sample_74, Sample_75, Sample_76, Sample_77, Sample_78, Sample_79, Sample_80, Sample_81, Sample_82, Sample_83, Sample_84, Sample_85, Sample_86, Sample_87, Sample_88, Sample_89, Sample_90, Sample_91, Sample_92, Sample_93, Sample_94, Sample_95, Sample_96, Sample_97, Sample_98, Sample_99, Sample_100, ...]

[10000 rows x 0 columns]

In [5]:
# phased genotype (n_snp, n_indiv, 2)
dset.geno

dask.array<concatenate, shape=(15357, 10000, 2), dtype=float32, chunksize=(1024, 10000, 2), chunktype=numpy.ndarray>

In [6]:
# local ancestry (n_snp, n_indiv, 2)
dset.lanc

dask.array<concatenate, shape=(15357, 10000, 2), dtype=int8, chunksize=(1024, 10000, 2), chunktype=numpy.ndarray>

In [7]:
# subset the first 50 SNPs
dset[0:50, :]

admix.Dataset object with n_snp x n_indiv = 50 x 10000, n_anc=2
	snp: 'CHROM', 'POS', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO'

In [8]:
# subset the first 50 individuals
dset[:, 0:50]

admix.Dataset object with n_snp x n_indiv = 15357 x 50, n_anc=2
	snp: 'CHROM', 'POS', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO'

In [9]:
# subset the first 50 SNPs and first 50 individuals
dset[0:50:, 0:50]

admix.Dataset object with n_snp x n_indiv = 50 x 50, n_anc=2
	snp: 'CHROM', 'POS', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO'

In [10]:
# calculate allele per ancestry backgrounds
dset.allele_per_anc()

dask.array<lambda, shape=(15357, 10000, 2), dtype=float64, chunksize=(1024, 10000, 2), chunktype=numpy.ndarray>

In [11]:
# calculate allele frequencies per ancestry backgrounds
dset.af_per_anc()

admix.data.af_per_anc: 100%|███████████████████████████████████████████████████████████████████████████████| 15/15 [00:11<00:00,  1.35it/s]

array([[0.28433613, 0.01600149],
       [0.44607595, 0.46056075],
       [0.25962513, 0.01133815],
       ...,
       [0.1228952 , 0.01448099],
       [0.34757477, 0.55327383],
       [0.17893943, 0.36445915]])